### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by NishinoTSK** [nipdep/img-ann#11]
I have in a1 all xml files of my dataset in this case have "1.xml" and in i1 all img files in this case have "1.jpg" this a test to see if convertor works for me and is giving the following error the current dataset is annoted in PascalVOC format
![error](https://user-images.githubusercontent.com/53551043/123482979-722ceb80-d5dc-11eb-9d2c-20ee4df1f04d.png)
: 
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/Projeto/Data Augmentation/nTrain/a1\\1.xml'

**Comment by nipdep** [comment]
Thanks for the update.
I have resolved the mentioned issue and published a patch version on
imgann-0.7.3 <https://pypi.org/project/imgann/> and you can update by `pip
install imgann -U'

**Comment by NishinoTSK** [comment]
It's converting now but i have another question if you can answer i appreciate it, in this example i converted PascalVoc to COCO 
but in the resulting file all fields have quotes-("") per example:
"annotations": [{"id": "1", "image_id": "1", "category_id": "1", "area": "1470840", "bbox": "[593, 1081, 2035, 2101]", "ignore": "0", "iscrowd": "0"
but according to this COCO format website "https://cocodataset.org/#format-data" the fields id per example is type int. I used another dataset in COCO format and it worked, but in some fields it didn't have quotes per example:
"annotations": [{"id": 1, "image_id": 1, "category_id": 1, "area": 1470840, "bbox": [593, 1081, 2035, 2101], "ignore": 0, "iscrowd": 0

The question is I have to fix the file myself, or is it a conversion problem or is it a problem with my reader in this case I'm using kwcoco (https://pypi.org/project/kwcoco/)

**Comment by nipdep** [comment]
the way you purpose is the proper one. but the library was outputting a
complete set of strings because the 'json' library can not write 'int32'
data into a .json file.
However I have managed to update the code to write a .json file with 'int'
dtype objects.
For that you have to update the current version `pip install imgann -U`.
I'm really sorry for the inconvenience and thank you for the issue.

**Comment by NishinoTSK** [comment]
Hi again unfortunately I believe the bbox notation in COCO format is still wrong I managed to fix it when reading my code but when I try to convert it back to PascalVOC format the same error appears, which I fixed when reading, I should make this change in the file itself or the tool itself does it for me? The error in question is what appears in the screenshot below.

![bbox](https://user-images.githubusercontent.com/53551043/123557395-0b880900-d767-11eb-8fb2-a71b299d170a.png)

**Comment by nipdep** [comment]
I really appreciate your support and thanks again.
The above was not a generic error, it occurred because of my mistake in a
previous bug fix [it saves as bbox in string format].
That error is resolved in the new `imgann` patch version.
And sorry for the inconvenience.

**Comment by NishinoTSK** [comment]
The above bug has been fixed but there is still a problem, when i convert from COCO format to Pascal VOC the bbox values ​​are all wrong, i have no idea what it might be. 
You can see this error in screenshot below where the file named "real" is my original Pascal VOC file while the file named "converted" was converted to COCO format and then converted back to Pascal VOC

![screenshot](https://user-images.githubusercontent.com/53551043/123636512-57808f80-d7f3-11eb-8365-db1d1e71a80c.png)

**Comment by nipdep** [comment]
Now, I'm really embarrassed about these bugs😅.I'm really sorryyyyy again🤓
new release has resolved above bug.
As matter of fact it happens because I have missed translating bounding box
format from KITTI2 to normalized.
And thanks for still try to use my buggy library🙇 and inform bugs. I
really appreciate !

**Comment by NishinoTSK** [comment]
Hi again when I convert from Pascal VOC to COCO and convert back to Pascal VOC it is correct now, but on the first conversion from Pascal VOC to COCO this COCO file the bounding box still seems to be wrong.
I compared it with a file reference generated by the roboflow site that also makes this conversion but with all the wrong categories, but the correct bouding box and it seems that the conversion by the imgann library is hitting the width, height correctly but missing x and y as I show in the screenshot. I also show in the screenshot as bounding_box reading the COCO format in the image.
Now I don't know if it's correct because when converting the COCO format to Pascal VOC the conversion is right and I'm the one plotting the bbox wrong or the COCO format is wrong.

![Roboflow](https://user-images.githubusercontent.com/53551043/123669278-4bf09100-d812-11eb-8dbc-9bfbce4509c4.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![imgann library](https://user-images.githubusercontent.com/53551043/123669466-7cd0c600-d812-11eb-8767-006ded5aa47a.png)
--------------------------------------------------------------------------------------------------------------------------------------------
![bbox in image](https://user-images.githubusercontent.com/53551043/123669000-0b911300-d812-11eb-9d6f-e6cf567a422a.png)

**Comment by nipdep** [comment]
could you send Robotflow.json , imgann library.json file to me to check-up
further [ if it is okay to share those data else could you send 2 .json
file that contains one image complete details [image, annotation and class
sections]]
And I'll definitely recheck on the implementation bug in the library.
thanks again🤓

**Comment by NishinoTSK** [comment]
Ok i send the first dataset (first arquive) in Pascal VOC annotation, this
dataset that i converted to COCO. Imgaan(imgann converted 'first
archive' to COCO) and Roboflow.json

Em seg., 28 de jun. de 2021 às 13:54, nipun deelaka <
***@***.***> escreveu:

> could you send Robotflow.json , imgann library.json file to me to check-up
> further [ if it is okay to share those data else could you send 2 .json
> file that contains one image complete details [image, annotation and class
> sections]]
> And I'll definitely recheck on the implementation bug in the library.
> thanks again🤓
>

**Comment by NishinoTSK** [comment]
Tried to email the files if they weren't, I uploaded them to this repository(https://github.com/NishinoTSK/Imgann-Tests)

**Comment by nipdep** [comment]
thanks, I'll look into it.

**Comment by nipdep** [comment]
🤓 This time library works correctly.
answer - 1 :
[ FOR : obj_id and img_id different between Roboflow.json and
imgann.voc2coco() generated .json file]
.xml files do not carries obj_id or img_id as a attribute of it. Os,
usually that value generated by the library itself [both in Roboflow and
imgann] therefore for a same image different libraries can generate
different ids.

answer -2:
[ FOR : bounding box misplacement]
in the robotflow KITTI format is [xmin, ymin, width, heigth] but usually
[in imgann] KITTI format is [x_center, y_center, width, heigth]
PROOF :
[image: Screenshot (35)_LI.jpg]
[image: Screenshot (36).png]
[image: Screenshot (38)_LI.jpg]
[image: Screenshot (40)_LI.jpg]

As a gratitude for showing bug/issues in my library and roboflow coco files
are frequently used in CV
I have updated imgann to support this new KITTI bbox format as well.
best regards.

**Comment by NishinoTSK** [comment]
Thanks for all the support I really appreciate I'm new to this area of ​​computer vision so I lack knowledge, could you show these screenshots later because I couldn't see them in the comment above. Just one last doubt you said that you updated the library for this new KITTI bbox format, but it was supposed to have changed something in the values ​​of the bbox in relation to version 0.76? Because I ran this new version and gave the same values. I haven't been able to see your screenshots yet so I have this next doubt, in this KITTI format [x_center, y_center, width, height] is my code that is wrong to view the bounding box. Anyway I will keep looking for a way to display the bbox correctly.
![MyCode](https://user-images.githubusercontent.com/53551043/123711067-36955a00-d846-11eb-8f45-d55cbdd7454b.png)

**Comment by nipdep** [comment]
missed screenshot in the above email. I hope you can see those now.

**Comment by nipdep** [comment]
About the new update :
I updated documentation for that new feature. It's not a new functionality
actually. In function related to 'coco' format there is a new parameter
called 'center', by default it takes `True` as value but for roboflow
datasets set 'center' parameter to `False`.  And I hope add more details
into documentation as well.
----------------------------------------------------------------------------------------------------------------------------------
*As a matter of fact
Why there were those bugs is because it's really hard to run unit tests or
integrated tests for library because most of them directly depend on
datafiles you provide, so `mocking object` or `synthetic datasets` is not
enough.
----------------------------------------------------------------------------------------------------------------------------------
sorry if they was any inconvenience
Thank you for the support
best of luck with your new project.
🙇If there are any error in imgann, please let me know.

**Comment by nipdep** [comment]
![Screenshot (35)_LI](https://user-images.githubusercontent.com/46063855/123815057-cd7c1800-d913-11eb-98ce-9dcd11a5ca71.jpg)
![Screenshot (36)](https://user-images.githubusercontent.com/46063855/123815125-da007080-d913-11eb-9abf-feca89cc2374.png)
![Screenshot (38)_LI](https://user-images.githubusercontent.com/46063855/123815157-dec52480-d913-11eb-920f-405493c54061.jpg)
![Screenshot (40)_LI](https://user-images.githubusercontent.com/46063855/123815182-e4bb0580-d913-11eb-9398-4da3f154fc19.jpg)
above image problem happened because I replied to issue by email.

**Comment by nipdep** [comment]
also this is not the active repository of [imgann](https://github.com/nipdep/imgann/) library,
link for active repository : https://github.com/nipdep/imgann/

**Comment by NishinoTSK** [comment]
Thank you very much for the support setting Center as false I was able to use the tool the way I wanted, this library will really help me.

**Comment by nipdep** [comment]
glad to hear that!
thanks you too for the support.
